name: generate_bitly_url
description: A appwrite dart cloud function to shorten long urls using bitly api.

version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  http: ^0.13.3

dev_dependencies:
  lints: ^1.0.0
